name: Web Validate

on: push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build project
        run: yarn && yarn build

      - name: Install COS
        run: sudo pip install coscmd

      - name: configure COS
        run: coscmd config -a ${{ secrets.COS_SECRET_ID }} -s ${{ secrets.COS_SECRET_KEY }} -b ${{ secrets.COS_BUCKET }} -r ap-nanjing

      - name: Upload to COS
        run: coscmd upload -r ./dist/ /
